services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - ./:/workspace
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    tty: true
    stdin_open: true
    command: ['bash', '-lc', 'make run PRESET=dev-docker ARGS="${STARDUST_ARGS:--v}"']
    ports:
      - "${STARDUST_HTTP_PORT:-8080}:8080"
      - "${STARDUST_CAPNP_PORT:-4000}:4000"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - ./:/workspace
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    tty: true
    stdin_open: true
    command: ['bash', '-lc', 'make test PRESET=dev-docker']


