name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build dev image
        run: docker build -t stardust-dev .
      - name: Build release
        run: |
          docker run --rm -v "$PWD:/workspace" -w /workspace stardust-dev \
            bash -lc 'make release'
      - name: Run tests
        run: |
          docker run --rm -v "$PWD:/workspace" -w /workspace stardust-dev \
            bash -lc 'chmod +x ./build/release/stardust_tests || true; ./build/release/stardust_tests'